# Что за Workflow
name: "Build & Test"

# Когда он запускается
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Позволяет вручную запускать Workflow
  workflow_dispatch:

jobs:
  setup_and_build:
    name: Настройка и запуск билда
    # Контейнер, в котором запускается задание
    runs-on: ubuntu-latest

    # Шаги задания
    steps:
      - name: Печать окружения. Окружение — это интересно.
        run: env

      # Егор Тенсин кстати учился на Матмехе СПбГУ
      - name: Установка Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Установка make и некоторых других инструментов
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake

      - name: Берём исходники из Гита
        uses: actions/checkout@v4

      - name: Собираем программу
        run: |
          git submodule update --init
          cd 03.B.RISC-Z
          chmod +x ./build.sh
          ./build.sh

      - name: Сохраняем результаты билда для тестирования
        uses: actions/upload-artifact@v4
        with:
          name: riscz
          path: ${{ github.workspace }}/03.B.RISC-Z

  test:
    # Зависимости
    needs:
      - setup_and_build

    name: Тестирование

    # Контейнер, в котором запускается задание
    runs-on: ubuntu-latest

    # Шаги задания
    steps:
      - name: Загружаем результаты билда для тестирования
        uses: actions/download-artifact@v4
        with:
          name: riscz
          path: 03.B.RISC-Z

      # Да, оно не исполнимое после загрузки
      # См. https://github.com/actions/upload-artifact/issues/38
      - name: Запускаем тестирование (допустим =))
        run: |
          cd 03.B.RISC-Z
          chmod u+x ./run_tests.sh
          chmod u+x ./build/test/risc-z
          ./run_tests.sh